# Generated by Django 3.1.7 on 2021-03-04 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=132)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('time_zone', models.CharField(blank=True, max_length=50)),
                ('mozzart_code', models.CharField(blank=True, max_length=20)),
                ('casapariurilor_code', models.CharField(blank=True, max_length=120)),
                ('stanley_code', models.CharField(blank=True, max_length=150)),
                ('oddsportal_code', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='odds.competition')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('mozzart_name', models.CharField(blank=True, max_length=255)),
                ('casapariurilor_name', models.CharField(blank=True, max_length=255)),
                ('stanley_name', models.CharField(blank=True, max_length=255)),
                ('oddsportal_name', models.CharField(blank=True, max_length=255)),
                ('competitions', models.ManyToManyField(to='odds.Competition')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='odds.sport'),
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(max_length=64)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odds.bookmaker')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='odds.event')),
            ],
            options={
                'verbose_name_plural': 'Odds',
                'unique_together': {('event', 'bookmaker', 'bet_type')},
            },
        ),
        migrations.CreateModel(
            name='BetfairOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(max_length=32)),
                ('last_traded', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('back_odds', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('back_size', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('lay_odds', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('lay_size', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betfair_odds', to='odds.event')),
            ],
            options={
                'verbose_name_plural': 'BetfairOdds',
                'unique_together': {('event', 'bet_type')},
            },
        ),
    ]
