# Generated by Django 3.1.7 on 2021-03-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tonybet_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
