# Generated by Django 3.1.7 on 2021-03-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0002_competition_tonybet_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='tonybet_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
